// -------------------------------------------------------------
// 
// File Name: hdlsrc\Half_Adder\Half_Adder_HDL.v
// Created: 2026-04-14 12:07:17
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Half_Adder_HDL
// Source Path: Half_Adder/Half_Adder_HDL
// Hierarchy Level: 0
// Model version: 1.5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Half_Adder_HDL
          (A,
           B,
           Cout,
           Sum);


  input   A;
  input   B;
  output  Cout;
  output  Sum;




  assign Cout = A & B;


  assign Sum = A ^ B;


endmodule  // Half_Adder_HDL

